fix documentation url
BurntSushi/chan-signal pull request #22
Opened 2017-08-18 13:24 UTC by spacejam

2017-08-18 13:55 UTC, BurntSushi requested changes

2017-08-18 13:55 UTC, BurntSushi commented on Cargo.toml
> +documentation = "http://burntsushi.net/rustdoc/chan-signal/"
Thanks! But actually, while you're here, could you just change this to `https://docs.rs/chan-signal`? Could you also update the link in the README? Thanks!

2017-08-18 15:17 UTC, spacejam commented
@BurntSushi done!

2017-08-26 18:36 UTC, BurntSushi commented
@spacejam Could you update the link in the README please as well?

2017-08-27 09:08 UTC, closed without merging